{"uuid":"c5da2370-7a10-4cfe-8fda-a6453a227fd1","historyId":"93e166f8c058186819348752dcb3b1d","fullName":"Tests.AddRecruitmentLead.Add_recruitment_lead_creation","labels":[{"name":"package","value":"Tests.AddRecruitmentLead"},{"name":"testClass","value":"Tests.AddRecruitmentLead"},{"name":"testMethod","value":"Add_recruitment_lead_creation"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"appium"},{"name":"subSuite","value":"Tests.AddRecruitmentLead"},{"name":"host","value":"DESKTOP-SLVRT3G"},{"name":"thread","value":"5700@DESKTOP-SLVRT3G.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"Add_recruitment_lead_creation","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"Couldn't connect to host, port: your_imap_server, 993; timeout -1","trace":"com.sun.mail.util.MailConnectException: Couldn't connect to host, port: your_imap_server, 993; timeout -1;\n  nested exception is:\n\tjava.net.UnknownHostException: your_imap_server\r\n\tat com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:740)\r\n\tat javax.mail.Service.connect(Service.java:366)\r\n\tat javax.mail.Service.connect(Service.java:246)\r\n\tat Tests.AddRecruitmentLead.Add_recruitment_lead_creation(AddRecruitmentLead.java:355)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1597)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:819)\r\n\tat org.testng.TestRunner.run(TestRunner.java:619)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1228)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1134)\r\n\tat org.testng.TestNG.run(TestNG.java:1101)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: java.net.UnknownHostException: your_imap_server\r\n\tat java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)\r\n\tat java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)\r\n\tat java.base/java.net.Socket.connect(Socket.java:752)\r\n\tat java.base/java.net.Socket.connect(Socket.java:687)\r\n\tat com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:359)\r\n\tat com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:238)\r\n\tat com.sun.mail.iap.Protocol.<init>(Protocol.java:134)\r\n\tat com.sun.mail.imap.protocol.IMAPProtocol.<init>(IMAPProtocol.java:131)\r\n\tat com.sun.mail.imap.IMAPStore.newIMAPProtocol(IMAPStore.java:763)\r\n\tat com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:698)\r\n\t... 28 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1721971091891,"stop":1721971277016}